### ISSUE TITLE
[BUG] docker image 3.7.0

### ISSUE THREAD

**Issue by DjSni** [linuxserver/docker-xbackbone#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i get this on a link;
```error
{"message":"Request` without file attached.","version":"3.7.0"}
```
on the main site i get this error:
```error
400 Bad Request
The server cannot or will not process the request due to an apparent client error.
```

### Expected Behavior

a working site

### Steps To Reproduce

Updateing to latest version of XBackBone

### Environment

```markdown
- OS: Ubuntu 22.04
- Docker version 24.0.7, build afdd53b
- XBackBone 3.7.0
```

### CPU architecture

x86-64

### Docker creation

```bash
version: '3'
services:
  image:
    image: lscr.io/linuxserver/xbackbone:latest
    port:
      - 80:80
    environment:
      - PUID=998
      - PGID=998
      - TZ=Europe/Berlin
    volumes:
      - ./volumes/xbackbone/config:/config
    restart: unless-stopped
```

### Container logs

```bash
Message: Bad request.
File: /app/www/public/app/Controllers/TagController.php
Line: 26
Trace: #0 [internal function]: App\Controllers\TagController->addTag()
#1 /app/www/public/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#2 /app/www/public/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#3 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#4 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /app/www/public/app/Middleware/CheckForMaintenanceMiddleware.php(26): Slim\MiddlewareDispatcher->handle()
#6 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#7 /app/www/public/app/Middleware/AuthMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#8 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AuthMiddleware->__invoke()
#9 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#10 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#11 /app/www/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#12 /app/www/public/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#13 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectMiddleware->__invoke()
#14 /app/www/public/app/Middleware/LangMiddleware.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\LangMiddleware->__invoke()
#16 /app/www/public/app/Middleware/RememberMiddleware.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RememberMiddleware->__invoke()
#18 /app/www/public/bootstrap/app.php(105): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#20 /app/www/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#26 /app/www/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#27 /app/www/public/index.php(11): Slim\App->run()
#28 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
[2024-01-14 16:23:23] app.ERROR: 400 Bad Request
Type: Slim\Exception\HttpBadRequestException
Code: 400
Message: Bad request.
File: /app/www/public/app/Controllers/TagController.php
Line: 26
Trace: #0 [internal function]: App\Controllers\TagController->addTag()
#1 /app/www/public/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#2 /app/www/public/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#3 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#4 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#5 /app/www/public/app/Middleware/CheckForMaintenanceMiddleware.php(26): Slim\MiddlewareDispatcher->handle()
#6 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#7 /app/www/public/app/Middleware/AuthMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#8 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AuthMiddleware->__invoke()
#9 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#10 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#11 /app/www/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#12 /app/www/public/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#13 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectMiddleware->__invoke()
#14 /app/www/public/app/Middleware/LangMiddleware.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\LangMiddleware->__invoke()
#16 /app/www/public/app/Middleware/RememberMiddleware.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#17 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RememberMiddleware->__invoke()
#18 /app/www/public/bootstrap/app.php(105): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#19 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#20 /app/www/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#21 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#22 /app/www/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#23 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#24 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#25 /app/www/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#26 /app/www/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#27 /app/www/public/index.php(11): Slim\App->run()
#28 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
```

**Comment by barrelltitor** [comment]
The /login page also gives an error 500

A cached login works, but it's not useful as due to the error reported here nothing actually works

Reverting to 3.6.3-ls130 works as expected, so nothing seems to have been damaged

**Comment by thespad** [comment]
Please try clearing `/config/www/xbackbone/resources/cache` and `/config/www/xbackbone/resources/sessions` and see if that fixes the issue.

**Comment by fabsau** [comment]
> Please try clearing `/config/www/xbackbone/resources/cache` and `/config/www/xbackbone/resources/sessions` and see if that fixes the issue.

Going into the container and deleting the contents fixed the issue for me. thanks!

**Comment by thespad** [comment]
Cool, I've opened a PR to fix the issue more broadly, but in the interim this should get people working with 3.7.0 upgrades.

**Comment by painteau** [comment]
I had the same issue since 3.7.0 update.
I cleaned like said before :

`rm -rvf /config/www/xbackbone/resources/cache/*`
`rm -rvf /config/www/xbackbone/resources/sessions/*`


Then i restarted my xbackbone docker container and it worked like a charm !

**Comment by DjSni** [comment]
Thanks for the fix, only I get the error:
```logs
500 Internal Server Error
Unexpected error while handling the request.
```
When I select a theme.
Logs:
```logs
[2024-01-15 17:01:23] app.ERROR: 500 Internal Server Error
Type: Slim\Exception\HttpInternalServerErrorException
Code: 500
Message: Internal server error.
File: /app/www/public/app/Controllers/SettingController.php
Line: 84
Trace: #0 /app/www/public/app/Controllers/SettingController.php(50): App\Controllers\SettingController->applyTheme()
#1 [internal function]: App\Controllers\SettingController->saveSettings()
#2 /app/www/public/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#3 /app/www/public/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#4 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#5 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#6 /app/www/public/app/Middleware/AdminMiddleware.php(28): Slim\MiddlewareDispatcher->handle()
#7 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AdminMiddleware->__invoke()
#8 /app/www/public/app/Middleware/CheckForMaintenanceMiddleware.php(26): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#9 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#10 /app/www/public/app/Middleware/AuthMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AuthMiddleware->__invoke()
#12 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#14 /app/www/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#15 /app/www/public/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#16 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectMiddleware->__invoke()
#17 /app/www/public/app/Middleware/LangMiddleware.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#18 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\LangMiddleware->__invoke()
#19 /app/www/public/app/Middleware/RememberMiddleware.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#20 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RememberMiddleware->__invoke()
#21 /app/www/public/bootstrap/app.php(105): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#22 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#23 /app/www/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#24 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#25 /app/www/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#26 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#27 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#28 /app/www/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#29 /app/www/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#30 /app/www/public/index.php(11): Slim\App->run()
#31 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
[2024-01-15 17:05:28] app.ERROR: 500 Internal Server Error
Type: Slim\Exception\HttpInternalServerErrorException
Code: 500
Message: Internal server error.
File: /app/www/public/app/Controllers/SettingController.php
Line: 84
Trace: #0 /app/www/public/app/Controllers/SettingController.php(50): App\Controllers\SettingController->applyTheme()
#1 [internal function]: App\Controllers\SettingController->saveSettings()
#2 /app/www/public/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array()
#3 /app/www/public/vendor/php-di/slim-bridge/src/ControllerInvoker.php(47): Invoker\Invoker->call()
#4 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(384): DI\Bridge\Slim\ControllerInvoker->__invoke()
#5 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#6 /app/www/public/app/Middleware/AdminMiddleware.php(28): Slim\MiddlewareDispatcher->handle()
#7 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AdminMiddleware->__invoke()
#8 /app/www/public/app/Middleware/CheckForMaintenanceMiddleware.php(26): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#9 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\CheckForMaintenanceMiddleware->__invoke()
#10 /app/www/public/app/Middleware/AuthMiddleware.php(33): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\AuthMiddleware->__invoke()
#12 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /app/www/public/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#14 /app/www/public/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#15 /app/www/public/app/Middleware/InjectMiddleware.php(21): Slim\Routing\RouteRunner->handle()
#16 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectMiddleware->__invoke()
#17 /app/www/public/app/Middleware/LangMiddleware.php(25): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#18 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\LangMiddleware->__invoke()
#19 /app/www/public/app/Middleware/RememberMiddleware.php(39): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#20 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\RememberMiddleware->__invoke()
#21 /app/www/public/bootstrap/app.php(105): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#22 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): Closure->{closure}()
#23 /app/www/public/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#24 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#25 /app/www/public/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#26 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#27 /app/www/public/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#28 /app/www/public/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#29 /app/www/public/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#30 /app/www/public/index.php(11): Slim\App->run()
#31 {main}
Tips: To display error details in HTTP response set "displayErrorDetails" to true in the ErrorHandler constructor. [] []
```
In the system settings, I now also get the message "The folder has no write permissions." but I haven't changed anything, just updated the Docker container. I didn't have this problem with version 3.6.x.

**Comment by thespad** [comment]
I think I might know why, let me check something.

**Comment by DjSni** [comment]
thx working now @thespad
